### PR TITLE
Fix user input to require title, resolves #74

### LINKED ISSUE #74: Add logic to stop user from submitting blank title from frontend (give error message)

### PR DESCRIPTION
**Pull request by geet084**
Adjust props going into NoteItem refactor
Add error handling for blank title field & make it required
Refactor NoteItem map to forEach

### CODE REVIEW

File: src/components/NoteItem/NoteItem.js [hunk 1]
```diff
@@ -1,8 +1,7 @@
 import React from 'react'
 
 export const NoteItem = (props) => {
-  const { handleItemChange, handleItemDelete, toggleComplete } = props;
-  const { isCompleted, id, description } = props.item;
+  const { isCompleted, id, description, handleItemChange, handleItemDelete, toggleComplete } = props;
```
Comment (foxwellm) [inline src/components/NoteItem/NoteItem.js:4]: Thanks for unifying these

**Review by foxwellm — APPROVED** [review]

File: src/containers/NoteForm/NoteForm.js [hunk 2]
```diff
@@ -72,16 +73,20 @@ export class NoteForm extends Component {
...
       newItems = newItems.filter(item => item.description !== '')
     }
-    isEdit ? editNote(url, { id, title, items: newItems }) : postNote(url, { id, title, items: newItems })
-    this.setState({ redirect: true, items: newItems })
+    if (title !== '') {
+      isEdit ? editNote(url, { id, title, items: newItems }) : postNote(url, { id, title, items: newItems })
+      this.setState({ redirect: true, items: newItems })
+    } else {
+      this.setState({ errorMessage: 'Please provide a title', items: newItems })
+    }
```
Comment (ericweissman) [inline src/containers/NoteForm/NoteForm.js:89]: Nice work giving explicit feedback to user as to what is missing from their form!

**Review by ericweissman — APPROVED** [review]
